name: deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  migrate:
    name: Run Prisma Migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm -C packages/db prisma:generate

      - name: Migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm -C packages/db prisma:deploy

  deploy:
    name: Deploy to Railway
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Link Railway project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: Deploy API service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        working-directory: apps/api
        run: railway up --service ${{ secrets.RAILWAY_API_SERVICE || 'api' }}

      - name: Deploy Worker service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        working-directory: apps/worker
        run: railway up --service ${{ secrets.RAILWAY_WORKER_SERVICE || 'worker' }}

